package com.progra2.tarea2.clase_11;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AgregarPokemon extends javax.swing.JFrame {
    
    //variables para db
    Statement  estado; // lleva el estado de la conexion.
    Connection conexion;
    
    /**
     * Creates new form AgregarPokemon
     */
    public AgregarPokemon() {
        initComponents();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String JDBC_URL = "jdbc:mysql://localhost:3306/pokedex?zeroDateTimeBehavior=convertToNull&useSSL=false&useTimezone=true&serverTimezone=UTC";
            conexion = DriverManager.getConnection(JDBC_URL,"root","donald225");
            estado = conexion.createStatement();
        } catch (Exception e) {
            System.out.println("Error en:"+e.getMessage());
        }  
    }
    
    private void agregar(){

        try{
             
        String nombre, id, especie, habitat;
        nombre = TextField_Nombre.getText();
        id = TextField_Id.getText();
        especie = TextField_Especie.getText();
        habitat = TextField_Habitat.getText();
        
        estado.executeUpdate("insert into pokemon (id, name, species, habitat) values ('"+id+"','"+nombre+"','"+especie+"','"+habitat+"')");

        }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Id repetido");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Agregar = new javax.swing.JButton();
        Label_Nombre = new javax.swing.JLabel();
        Label_Id = new javax.swing.JLabel();
        Lavbel_Especie = new javax.swing.JLabel();
        Label_Habitat = new javax.swing.JLabel();
        TextField_Nombre = new javax.swing.JTextField();
        TextField_Id = new javax.swing.JTextField();
        TextField_Especie = new javax.swing.JTextField();
        TextField_Habitat = new javax.swing.JTextField();
        Button_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button_Agregar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button_Agregar.setText("Agregar");
        Button_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AgregarActionPerformed(evt);
            }
        });

        Label_Nombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Label_Nombre.setText("Nombre");

        Label_Id.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Label_Id.setText("Id");

        Lavbel_Especie.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Lavbel_Especie.setText("Especie");

        Label_Habitat.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Label_Habitat.setText("Habitat");

        TextField_Nombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        TextField_Id.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        TextField_Especie.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        TextField_Habitat.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        Button_Salir.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button_Salir.setText("Regresar");
        Button_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lavbel_Especie)
                    .addComponent(Label_Habitat)
                    .addComponent(Label_Nombre)
                    .addComponent(Label_Id)
                    .addComponent(Button_Agregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextField_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(TextField_Id, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(TextField_Especie))
                    .addComponent(TextField_Habitat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Button_Salir)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Id)
                    .addComponent(TextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Nombre)
                    .addComponent(TextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lavbel_Especie)
                    .addComponent(TextField_Especie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Habitat)
                    .addComponent(TextField_Habitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Agregar)
                    .addComponent(Button_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AgregarActionPerformed
        // TODO add your handling code here:
            agregar();
        
    }//GEN-LAST:event_Button_AgregarActionPerformed

    private void Button_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Button_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Agregar;
    private javax.swing.JButton Button_Salir;
    private javax.swing.JLabel Label_Habitat;
    private javax.swing.JLabel Label_Id;
    private javax.swing.JLabel Label_Nombre;
    private javax.swing.JLabel Lavbel_Especie;
    private javax.swing.JTextField TextField_Especie;
    private javax.swing.JTextField TextField_Habitat;
    private javax.swing.JTextField TextField_Id;
    private javax.swing.JTextField TextField_Nombre;
    // End of variables declaration//GEN-END:variables
}
